<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMV5zNcz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMV5zNcz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMV5zNcz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMV5zNcz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMV5zNcz\App_KernelDevDebugContainer([
    'container.build_hash' => 'MV5zNcz',
    'container.build_id' => '1636007b',
    'container.build_time' => 1651151967,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMV5zNcz');
