<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAHcxwcE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAHcxwcE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAHcxwcE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAHcxwcE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAHcxwcE\App_KernelDevDebugContainer([
    'container.build_hash' => 'AHcxwcE',
    'container.build_id' => '798dcdb6',
    'container.build_time' => 1652098121,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAHcxwcE');
