<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBDtW4M1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBDtW4M1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBDtW4M1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBDtW4M1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBDtW4M1\App_KernelDevDebugContainer([
    'container.build_hash' => 'BDtW4M1',
    'container.build_id' => 'b02121fa',
    'container.build_time' => 1651159104,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBDtW4M1');
